apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    control-plane: {{ .Values.plugin }}
  name: {{ .Values.plugin }}-config
  namespace: {{ .Values.namespace }}
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: 0.0.0.0:8081
    metrics:
      bindAddress: 0.0.0.0:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: {{ .Values.plugin }}.katanomi.dev
