apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.plugin }}
  namespace: {{ .Values.namespace }}
{{-  if .Values.registry.imagePullSecrets }}
imagePullSecrets:
{{- range $index, $secret := .Values.registry.imagePullSecrets }}
{{- if $secret }}
- name: {{ $secret | quote}}
{{- end }}
{{- end }}
{{- end }}
